spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/LogiTrack_pro
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate